### PR TITLE
Fixed Issue #2

### PR DESCRIPTION
**Pull request by ghost**
* Refactoring of some methods, especially when determing stringvalue of
ActionType enum. (Replaced switch by for-loop to automatically support
additional types)
* Replaced unicode character with unicode sequence
* Fixed ban command, now works with names

### CODE REVIEW

**Comment by KasperFranz** [comment]
I don't think that the x and str gives anything to the understanding of what the variable is used for.

to help the understanding of the variable should be the job of the IDE and not the code

**Comment by ghost** [comment]
Well it doesn't tell you what the variable is used for. That's what the actual name is for. But it tells you something about the type and helps you work faster with it. Also of course it is the job of the IDE to inform you what type the variable is, but there you rely on an IDE which supports that feature. That is not always guaranteed.

**Comment by KasperFranz** [comment]
can i get you to change the x, str and Int type pend because IMO it doesn't give any value.

And the general in Java development is not to have the type prepended to the variable

**Comment by ghost** [comment]
Removed the prefixes

**Pull request merged**
